import { dialog, BrowserWindow, app, shell } from 'electron';
import fs from 'fs';
import path from 'path';
import { randomUUID } from 'crypto';
import { LibreOfficeProvider } from './libreOfficeProvider';
import { handleTrusted, requireBinary } from '../../security';

const provider = new LibreOfficeProvider();

// Job Registry
const activeJobs = new Map<string, { abortController: AbortController, tempDir: string }>();

// Input / output size guards
const MAX_INPUT_PPTX_BYTES = 300 * 1024 * 1024;
const MAX_CONVERTED_PDF_BYTES = 500 * 1024 * 1024;

const TEMP_DIR_PREFIX = 'malipdf-pptx-';
const PRESENTATION_EXTENSIONS = ['.pptx', '.ppt', '.odp'];
export const LIBREOFFICE_DOWNLOAD_URL = 'https://www.libreoffice.org/download/download-libreoffice/';
/** Temp folders older than this are leftovers of a crash and are removed at startup. */
const STALE_TEMP_AGE_MS = 24 * 60 * 60 * 1000;

/** Job ids are generated by the renderer; accept only short safe tokens. */
function requireJobId(value: unknown): string {
  if (typeof value !== 'string' || !/^[A-Za-z0-9_-]{1,64}$/.test(value)) {
    throw new TypeError('Invalid conversion job id.');
  }
  return value;
}

async function removeStaleTempDirs(): Promise<void> {
  const tempRoot = app.getPath('temp');
  let entries: fs.Dirent[];
  try {
    entries = await fs.promises.readdir(tempRoot, { withFileTypes: true });
  } catch {
    return;
  }
  const now = Date.now();
  await Promise.all(entries
    .filter((entry) => entry.isDirectory() && entry.name.startsWith(TEMP_DIR_PREFIX))
    .map(async (entry) => {
      const dir = path.join(tempRoot, entry.name);
      try {
        const stats = await fs.promises.stat(dir);
        if (now - stats.mtimeMs > STALE_TEMP_AGE_MS) {
          await fs.promises.rm(dir, { recursive: true, force: true });
        }
      } catch {
        // Ignore: best-effort housekeeping.
      }
    }));
}

/** Abort running conversions (LibreOffice is SIGKILLed; temp dirs are removed by each job). */
export function abortAllPptxJobs(): void {
  for (const job of activeJobs.values()) job.abortController.abort();
}

/**
 * Convert one presentation in a private temp folder. `writeInput` puts the
 * presentation at the given (generated) path, so LibreOffice never sees the
 * user's own file path.
 */
async function convertJob(
  jobId: string,
  extension: string,
  displayName: string,
  writeInput: (target: string) => Promise<void>,
): Promise<{ buffer: ArrayBuffer; name: string }> {
  if (activeJobs.has(jobId)) throw new Error(`Job ID ${jobId} is already active.`);
  const tempDir = await fs.promises.mkdtemp(path.join(app.getPath('temp'), TEMP_DIR_PREFIX));
  const abortController = new AbortController();
  activeJobs.set(jobId, { abortController, tempDir });
  try {
    await fs.promises.chmod(tempDir, 0o700).catch(() => {});
    const safeInputPath = path.join(tempDir, `input-${randomUUID()}${extension}`);
    await writeInput(safeInputPath);
    if (abortController.signal.aborted) throw new Error('Conversion aborted by user.');

    const pdfPath = await provider.convertToPdf(safeInputPath, tempDir, abortController.signal);

    const stats = await fs.promises.stat(pdfPath);
    if (stats.size > MAX_CONVERTED_PDF_BYTES) {
      throw new Error(`Converted PDF exceeds the 500MB size limit (was ${Math.round(stats.size / 1024 / 1024)}MB).`);
    }
    const pdfBuffer = await fs.promises.readFile(pdfPath);
    const exact = pdfBuffer.buffer.slice(pdfBuffer.byteOffset, pdfBuffer.byteOffset + pdfBuffer.byteLength) as ArrayBuffer;
    return { buffer: exact, name: displayName };
  } finally {
    activeJobs.delete(jobId);
    try {
      await fs.promises.rm(tempDir, { recursive: true, force: true });
    } catch (err) {
      console.error(`Failed to cleanup temp directory ${tempDir}:`, err);
    }
  }
}

export function setupPptxIpc(isDev: boolean) {
  app.whenReady().then(() => { void removeStaleTempDirs(); });
  app.on('will-quit', abortAllPptxJobs);

  // Fixed URL: the renderer cannot choose what gets opened.
  handleTrusted('pptx:openLibreOfficeDownload', isDev, async () => {
    await shell.openExternal(LIBREOFFICE_DOWNLOAD_URL);
    return true;
  });

  handleTrusted('pptx:isAvailable', isDev, async () => {
    return await provider.isAvailable();
  });

  handleTrusted('pptx:startConversion', isDev, async (event, rawJobId: unknown) => {
    const jobId = requireJobId(rawJobId);
    if (activeJobs.has(jobId)) {
      throw new Error(`Job ID ${jobId} is already active.`);
    }

    // 1. Validate Provider
    const isAvailable = await provider.isAvailable();
    if (!isAvailable) {
      throw new Error('PowerPoint to PDF conversion is not available on this system (LibreOffice not found).');
    }

    // 2. User selects PPTX file
    const window = BrowserWindow.fromWebContents(event.sender);
    if (!window) return null;
    const result = await dialog.showOpenDialog(window, {
      title: 'Insert PowerPoint Printout',
      filters: [{ name: 'PowerPoint Presentations', extensions: ['pptx'] }],
      properties: ['openFile'],
    });

    if (result.canceled || result.filePaths.length === 0) {
      return null;
    }

    const inputPath = result.filePaths[0];
    const inputStats = await fs.promises.stat(inputPath);
    if (inputStats.size > MAX_INPUT_PPTX_BYTES) {
      throw new Error(`The presentation is larger than ${MAX_INPUT_PPTX_BYTES / 1024 / 1024} MB.`);
    }
    return convertJob(jobId, '.pptx', path.basename(inputPath), (target) => fs.promises.copyFile(inputPath, target));
  });

  // Drag & drop: the renderer sends the dropped file's bytes (it has no path).
  handleTrusted('pptx:convertBytes', isDev, async (_event, rawJobId: unknown, rawData: unknown, rawName: unknown) => {
    const jobId = requireJobId(rawJobId);
    const data = requireBinary(rawData, 'Presentation', MAX_INPUT_PPTX_BYTES);
    const name = typeof rawName === 'string' ? path.basename(rawName).slice(0, 255) : 'Presentation.pptx';
    const extension = path.extname(name).toLowerCase();
    if (!PRESENTATION_EXTENSIONS.includes(extension)) {
      throw new Error('Only PowerPoint (.pptx, .ppt) and OpenDocument (.odp) presentations can be converted.');
    }
    if (!(await provider.isAvailable())) {
      throw new Error('PowerPoint to PDF conversion is not available on this system (LibreOffice not found).');
    }
    return convertJob(jobId, extension, name, (target) => fs.promises.writeFile(target, data, { mode: 0o600 }));
  });

  handleTrusted('pptx:cancelConversion', isDev, async (_event, rawJobId: unknown) => {
    const job = activeJobs.get(requireJobId(rawJobId));
    if (job) {
      // The job's finally block removes the temp dir once LibreOffice exits.
      job.abortController.abort();
    }
  });
}
